version: '3.8'
services:

    nginx:
        image: nginx:stable-alpine
        restart: always
        links:
            - app
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - app
        volumes:
            - ./docker/conf/nginx_default.conf:/etc/nginx/conf.d/default.conf
            - ./storage/app/public:/usr/share/nginx/html/storage

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
